<?xml version="1.0" encoding="utf-8"?>
<AddOnRegData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" SlientInstallation="No" SlientUpgrade="No" Partnernmsp="Andersen Consulting" SchemaVersion="3.0" Type="" MultipleVersion="false" OnDemand="" OnPremise="" ExtName="AndersenB1Tax" ExtVersion="1.0.0.0" Contdata="" Partner="Andersen Consulting" DBType="HANA" ClientType="A">
  <Validity>
    <SBOCompatibility>
      <Version From="" To="" />
    </SBOCompatibility>
  </Validity>
  <Configuration>
    <Repository>
      <Properties />
    </Repository>
    <Deployment>
      <Properties />
    </Deployment>
    <Assignment>
      <Properties />
    </Assignment>
  </Configuration>
  <Addons>
    <Addon Name="" Group="" ForceFlag="" Visible="" AutoAssign="" SelfUpgrd="">
      <x86 AddonExe="" AddonSig="">
        <Installation>
          <Files />
        </Installation>
        <Uninstallation>
          <Files />
        </Uninstallation>
      </x86>
      <x64 AddonExe="AAC.TaxDeterminationImporter.exe" AddonSig="">
        <Installation>
          <Files>
            <File FileName="AAC.TaxDeterminationImporter.Core.dll">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.Core.pdb">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.exe">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.exe.config">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.pdb">
              <Actions />
            </File>
            <File FileName="ClosedXML.dll">
              <Actions />
            </File>
            <File FileName="DocumentFormat.OpenXml.dll">
              <Actions />
            </File>
            <File FileName="ExcelNumberFormat.dll">
              <Actions />
            </File>
            <File FileName="FastMember.dll">
              <Actions />
            </File>
            <File FileName="SBO.Hub.dll">
              <Actions />
            </File>
            <File FileName="Views\FrmImportLog.srf">
              <Actions />
            </File>
            <File FileName="Views\FrmRemoveTax.srf">
              <Actions />
            </File>
          </Files>
        </Installation>
        <Uninstallation>
          <Files>
            <File FileName="AAC.TaxDeterminationImporter.Core.dll">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.Core.pdb">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.exe">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.exe.config">
              <Actions />
            </File>
            <File FileName="AAC.TaxDeterminationImporter.pdb">
              <Actions />
            </File>
            <File FileName="ClosedXML.dll">
              <Actions />
            </File>
            <File FileName="DocumentFormat.OpenXml.dll">
              <Actions />
            </File>
            <File FileName="ExcelNumberFormat.dll">
              <Actions />
            </File>
            <File FileName="FastMember.dll">
              <Actions />
            </File>
            <File FileName="SBO.Hub.dll">
              <Actions />
            </File>
            <File FileName="Views\FrmImportLog.srf">
              <Actions />
            </File>
            <File FileName="Views\FrmRemoveTax.srf">
              <Actions />
            </File>
          </Files>
        </Uninstallation>
      </x64>
    </Addon>
  </Addons>
  <XApps>
    <XApp Name="" Path="" FileName="" />
  </XApps>
  <UDQs>
    <UDQ udqname="">
      <Hana FileName="" />
    </UDQ>
  </UDQs>
</AddOnRegData>
